[package]
name = "blackhole-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
blackhole = { path = "..", default-features = false }
libfuzzer-sys = "0.4"

[[bin]]
name = "query_view"
path = "fuzz_targets/query_view.rs"
test = false
doc = false
